USE [master]
GO
/****** Object:  Database [SabrisKontaktManager]    Script Date: 08.01.2019 15:52:54 ******/
CREATE DATABASE [SabrisKontaktManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SabrisKontaktManager', FILENAME = N'C:\Users\david\SabrisKontaktManager.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SabrisKontaktManager_log', FILENAME = N'C:\Users\david\SabrisKontaktManager_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SabrisKontaktManager] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SabrisKontaktManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SabrisKontaktManager] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET ARITHABORT OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SabrisKontaktManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SabrisKontaktManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SabrisKontaktManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SabrisKontaktManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SabrisKontaktManager] SET  MULTI_USER 
GO
ALTER DATABASE [SabrisKontaktManager] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SabrisKontaktManager] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SabrisKontaktManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SabrisKontaktManager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SabrisKontaktManager] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SabrisKontaktManager] SET QUERY_STORE = OFF
GO
USE [SabrisKontaktManager]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [SabrisKontaktManager]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 08.01.2019 15:52:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[People]    Script Date: 08.01.2019 15:52:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[People](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[Age] [int] NOT NULL,
	[FK_CategoryId] [int] NOT NULL,
 CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[People]  WITH CHECK ADD  CONSTRAINT [FK_People_Categories] FOREIGN KEY([FK_CategoryId])
REFERENCES [dbo].[Categories] ([Id])
GO
ALTER TABLE [dbo].[People] CHECK CONSTRAINT [FK_People_Categories]
GO
USE [master]
GO
ALTER DATABASE [SabrisKontaktManager] SET  READ_WRITE 
GO
